import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";
import { vazirFont } from "./fonts";
import { CacheProvider } from "./CacheProvider";
import StoreProvider from "./components/Providers/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${vazirFont.className} antialiased`}>
        <StoreProvider>
          <CacheProvider>
            <ThemeProvider theme={theme}>{children}</ThemeProvider>
          </CacheProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
