import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";
import { IranSansXFont } from "./fonts";
import StoreProvider from "./components/Providers/StoreProvider";
import { CacheProvider } from "./components/Providers/CacheProvider";
import { AuthProvider } from "./components/Providers/AuthProvider";
import { SnackbarProvider } from "./components/Providers/SnackbarProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${IranSansXFont.className} antialiased`}>
        <div className="flex min-h-screen flex-col">
          <main className="flex-1">
            <StoreProvider>
              <CacheProvider>
                <ThemeProvider theme={theme}>
                  <AuthProvider>
                    <SnackbarProvider>{children}</SnackbarProvider>
                  </AuthProvider>
                </ThemeProvider>
              </CacheProvider>
            </StoreProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
