import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";
import { vazirFont } from "./fonts";
import StoreProvider from "./components/Providers/StoreProvider";
import { CacheProvider } from "./components/Providers/CacheProvider";
import { AuthProvider } from "./components/Providers/AuthProvider";
import { SnackbarProvider } from "./components/Providers/SnackbarProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${vazirFont.className} antialiased`}>
        <StoreProvider>
          <CacheProvider>
            <ThemeProvider theme={theme}>
              <AuthProvider>
                <SnackbarProvider>{children}</SnackbarProvider>
              </AuthProvider>
            </ThemeProvider>
          </CacheProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
